//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarAirRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int AsgType { get; set; }
        public int FlightId { get; set; }
        public int OtherId { get; set; }
        public int LeaveId { get; set; }
        public int GroundCourseId { get; set; }
        public int RestId { get; set; }
        public int PositioningId { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int CrewId { get; set; }
        public string CreatedBy { get; set; }
        public bool AsgActiv { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Crew Crew { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual GroundCours GroundCours { get; set; }
        public virtual Leaf Leaf { get; set; }
        public virtual NomActivity NomActivity { get; set; }
        public virtual Others Others { get; set; }
        public virtual Positioning Positioning { get; set; }
        public virtual Rest Rest { get; set; }
    }
}
