//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarAirRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public int CrewId { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Implied { get; set; }
        public string Signed { get; set; }
        public string EmployeeType { get; set; }
        public string AcfDomainLicense { get; set; }
    
        public virtual Crew Crew { get; set; }
    }
}
