//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarAirRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Assignments = new HashSet<Assignment>();
        }
    
        public int Id { get; set; }
        public System.DateTime ReportingTime { get; set; }
        public System.DateTime TakeOffTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public string FlightNumber { get; set; }
        public int AircraftId { get; set; }
        public System.DateTime EstimatedTakeOff { get; set; }
        public System.DateTime EstimatedArrival { get; set; }
        public int FlightTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual NomAircraft NomAircraft { get; set; }
    }
}
