//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarAirRoles.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<CrewPosition> CrewPositions { get; set; }
        public virtual DbSet<Crew> Crews { get; set; }
        public virtual DbSet<DelayCode> DelayCodes { get; set; }
        public virtual DbSet<FlightExperience> FlightExperiences { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<GroundCours> GroundCourses { get; set; }
        public virtual DbSet<Leaf> Leaves { get; set; }
        public virtual DbSet<Licence> Licences { get; set; }
        public virtual DbSet<NomActivity> NomActivities { get; set; }
        public virtual DbSet<NomAircraft> NomAircrafts { get; set; }
        public virtual DbSet<NomAirport> NomAirports { get; set; }
        public virtual DbSet<NomPosition> NomPositions { get; set; }
        public virtual DbSet<NomRule> NomRules { get; set; }
        public virtual DbSet<Others> Others { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<PersonalData> PersonalDatas { get; set; }
        public virtual DbSet<Positioning> Positionings { get; set; }
        public virtual DbSet<Rest> Rests { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<ScheduleChanx> ScheduleChanges { get; set; }
        public virtual DbSet<SSR> SSRs { get; set; }
        public virtual DbSet<TextMessage> TextMessages { get; set; }
    }
}
