//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarAirRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int Id { get; set; }
        public int CrewId { get; set; }
        public int PassNo { get; set; }
        public string PassLciId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        public virtual Crew Crew { get; set; }
    }
}
