//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarAirRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalData
    {
        public int Id { get; set; }
        public int CrewId { get; set; }
        public string Phone { get; set; }
        public string CarrierCode { get; set; }
        public string Email { get; set; }
        public System.DateTime CIExpiryDate { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string EmPhone { get; set; }
        public string EmCarrierCode { get; set; }
    }
}
