// <auto-generated />
namespace MarAirRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class other_tables2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(other_tables2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811051503080_other_tables2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
