// <auto-generated />
namespace MarAirRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_missing_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_missing_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201906101326450_db_missing_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
