// <auto-generated />
namespace MarAirRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class company_flt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(company_flt));
        
        string IMigrationMetadata.Id
        {
            get { return "201901261258318_company_flt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
