// <auto-generated />
namespace MarAirRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class details_flt_flg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(details_flt_flg));
        
        string IMigrationMetadata.Id
        {
            get { return "201901261251058_details_flt_flg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
